
development:
  adapter: postgresql
  database: store_development
  host: localhost
  pool: 5
  timeout: 5000

# test:
#   adapter: postgresql
#   database: store_test
#   pool: 5
#   timeout: 5000
# 
# production:
#   adapter: postgresql
#   database: store_production
#   pool: 5
#   timeout: 5000
